name: publish

on: [push]

jobs:
  publish-autotls-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Docker Image
      run: |
        docker build . --tag ghcr.io/corpus-solutions/autotls:latest
        docker run ghcr.io/corpus-solutions/autotls:latest
        docker push ghcr.io/corpus-solutions/autotls:latest
